### ISSUE TITLE
fix error in documentation build

### ISSUE THREAD

**Issue by MAfarrag** [Serapieum-of-alex/pyramids#78]
recheck the configuration of the readthedocs.yml  from https://docs.readthedocs.io/en/stable/config-file/v2.html

[pyramids] .readthedocs.yml (Lines 3-15)

```

# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
  environment: docs/environment.yml
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
#Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml
```

[Open in IDE](https://codestream-eu1.service.eu.newrelic.com/c/ZVlndyzrYykKHlpS/1OSw_8iTRHq0FnRiyWkKNQ?marker=659da988c05cca9e66dfa3be&ide=default&src=GitHub) · [Open on GitHub](https://github.com/serapieum-of-alex/pyramids/blob/175541312717ee571e08b9c32601c541c459758f/.readthedocs.yml#L3-L15)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
